version: "3"

services:
  capricornus:
    image: "jointhero/capricornus:latest"
    container_name: capricornus
    hostname: capricornus
    restart: unless-stopped
    depends_on:
      - arangodb
    environment:
      arangodb_hosts: "http://capricornus-arangodb:8529"
      app_profile: "demo"
    ports:
      - "8880:8880/tcp"
      - "8843:8843/tcp"
    networks:
      - capricornus

  arangodb:
    image: "arangodb"
    container_name: capricornus-arangodb
    hostname: capricornus-arangodb
    user: root
    restart: unless-stopped
    volumes:
      - /data/arangodb/data/arangodb3:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: "passw0rd"
    ports:
      - "8529:8529/tcp"
    networks:
      - capricornus

networks:
  capricornus:
    driver: bridge
